#define HAVE_STRUCT_STAT_ST_FLAGS 0
#define HAVE_STRUCT_STAT_ST_GEN 0
#define HAVE_STRUCT_STAT_ST_BIRTHTIME 0
#define HAVE_STRUCT_STAT_ST_MTIMENSEC 0
#define HAVE_DEVNAME 0
#define HAVE_STRUCT_STAT_ST_ATIM 1
